//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package com.ylq.demo1;

import android.app.ActivityManager;
import android.content.ComponentName;
import android.content.Context;
import android.content.Intent;
import android.support.v4.app.Fragment;
import org.androidannotations.api.BackgroundExecutor;

public final class FloatWindowService_
    extends FloatWindowService
{


    public static FloatWindowService_.IntentBuilder_ intent(Context context) {
        return new FloatWindowService_.IntentBuilder_(context);
    }

    public static FloatWindowService_.IntentBuilder_ intent(Fragment supportFragment) {
        return new FloatWindowService_.IntentBuilder_(supportFragment);
    }

    private void init_() {
        mActivityManager = ((ActivityManager) this.getSystemService(Context.ACTIVITY_SERVICE));
    }

    @Override
    public void onCreate() {
        init_();
        super.onCreate();
    }

    @Override
    public void reflush() {
        BackgroundExecutor.execute(new BackgroundExecutor.Task("Task", 0, "") {


            @Override
            public void execute() {
                try {
                    FloatWindowService_.super.reflush();
                } catch (Throwable e) {
                    Thread.getDefaultUncaughtExceptionHandler().uncaughtException(Thread.currentThread(), e);
                }
            }

        }
        );
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;
        private Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, FloatWindowService_.class);
        }

        public IntentBuilder_(Fragment fragment) {
            fragmentSupport_ = fragment;
            context_ = fragment.getActivity();
            intent_ = new Intent(context_, FloatWindowService_.class);
        }

        public Intent get() {
            return intent_;
        }

        public FloatWindowService_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public ComponentName start() {
            return context_.startService(intent_);
        }

        public boolean stop() {
            return context_.stopService(intent_);
        }

    }

}
